sensor:
  - platform: resistance
    id: resistance_sensor
    sensor: source_sensor
    configuration: UPSTREAM
    reference_voltage: 3.3V
    resistor: 100kOhm
    name: Resistance Sensor
    internal: true
    accuracy_decimals: 4