name: Build and Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      bypass-yaml-check:
        description: 'Bypass YAML change check (force build/publish)'
        type: boolean
        required: false
        default: false
  # release:
  #   types: [published]

jobs:
  build-and-publish:
    uses: ApolloAutomation/Workflows/.github/workflows/build.yml@main
    permissions:
      contents: write
      pages: write
      id-token: write
      pull-requests: write
    with:
      device-name: temp-1
      yaml-files: |
        Integrations/ESPHome/TEMP-1.yaml
        Integrations/ESPHome/TEMP-1B.yaml
        Integrations/ESPHome/TEMP-1_R2.yaml
        Integrations/ESPHome/TEMP-1B_R2.yaml
      firmware-names: "1:firmware,1B:firmware-b,1_R2:firmware2,1B_R2:firmware-b2"
      core-yaml-path: Integrations/ESPHome/Core.yaml
      esphome-version: stable
      # Bypass check if manually triggered with bypass option
      check-yaml-changes: ${{ !(github.event_name == 'workflow_dispatch' && github.event.inputs.bypass-yaml-check == 'true') }}
      publish-to-pages: true
      has-installer: true
      installer-path: static